name: modern-de-pipeline

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.10
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --check=false
      - --node-id
      - "0"
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:${REDPANDA_KAFKA_PORT:-19092}
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:${REDPANDA_KAFKA_PORT:-19092}
      - --pandaproxy-addr
      - internal://0.0.0.0:8082,external://0.0.0.0:${REDPANDA_HTTP_PROXY_PORT:-18082}
      - --advertise-pandaproxy-addr
      - internal://redpanda:8082,external://localhost:${REDPANDA_HTTP_PROXY_PORT:-18082}
      - --schema-registry-addr
      - internal://0.0.0.0:8081,external://0.0.0.0:${REDPANDA_SCHEMA_REGISTRY_PORT:-18081}
      - --rpc-addr
      - redpanda:33145
      - --advertise-rpc-addr
      - redpanda:33145
      - --default-log-level=info
    volumes:
      - redpanda-data:/var/lib/redpanda/data
      - ./bootstrap.yml:/etc/redpanda/.bootstrap.yaml
    ports:
      - ${REDPANDA_SCHEMA_REGISTRY_PORT:-18081}:18081
      - ${REDPANDA_HTTP_PROXY_PORT:-18082}:18082
      - ${REDPANDA_KAFKA_PORT:-19092}:19092
      - ${REDPANDA_ADMIN_PORT:-19644}:9644
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "-X", "brokers=localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10

  console:
    image: docker.redpanda.com/redpandadata/console:v3.7.4
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml && /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - ${REDPANDA_CONSOLE_PORT:-8080}:8080

volumes:
  redpanda-data:
